### PR TITLE
Shaocong dong

### PR DESCRIPTION
**Pull request by ShaocongDong**

### CODE REVIEW

**Review by nedlowe — COMMENTED** [review]
""""trans_type input is 0 or 1, 0 means buy and 1 means sell"""

That is part of the transaction object, not the asset.

**Review by nedlowe — COMMENTED** [review]
What are the "automobile_LOCAL_8720.py" and "BACKUP" etc files?  They shouldn't be checked in...?

**Review by nedlowe — COMMENTED** [review]
For things like "if (drive is None or drive == ''):" you can say "if not drive:".  The only case where this doesn't work is for when the value might be "0" (as that is considered negative).

**Review by nedlowe — COMMENTED** [review]
"if exercise_type == 'E' or exercise_type == 'A':"

Please see the option mixin and align with that.

**Comment by ShaocongDong** [comment]
Yes, they shouldn't be checked in. Sorry for the confusions.
Ok, I will change the class respectively.

**Comment by ShaocongDong** [comment]
The trans_type attribute is inside automobile class from the requirement documentation. It is a Boolean value signaling only buy or sell instead of having multiple transaction types like in transaction class.
Should it be also included in the automobile class definition?

**Comment by nedlowe** [comment]
The Asset classes should just describe the asset itself, not what is done with them.  Anything related to the purchase or sale of the asset should be on the Transaction class.

So essentially, the requirement document is wrong.

**Review by nedlowe — COMMENTED** [review]
Sorry I am going to be super pedantic :-)

1) manufac_year -> please make this manufacture_year, I hate shortening things.
2) Remove brackets around '(not XYZ)'
3) "Tradition" warrant -> "Traditional"
4) generic_formatted_string could maybe be put into amaasutils library, since it is repeated?

**Comment by ShaocongDong** [comment]
OK, I will make corresponding changes. Actually I am using only the data.py and utils.py for csv upload. I think utils.py can be put into amaasutils. Thank you.

**Comment by nedlowe** [comment]
Great, thank you

**Review by nedlowe — CHANGES_REQUESTED** [review]
there is a typo: .manufacure_year = manufacture_year

But actually, can you put 'model_year' please?  It's better naming.  Sorry for not pointing that out earlier.

**Review by nedlowe — APPROVED** [review]
Thanks for incorporating the requested changes.

**Pull request merged**
